#!/bin/bash -e

# Agregar las instrucciones para crear la estructura de carpetas
cd distribuidora

mkdir clientes
cd clientes

mkdir quinta-region
mkdir santiago
mkdir sexta-region

cd quinta-region
touch lista.xls
cd ..
cd santiago

mkdir la-pintana
mkdir maipu
mkdir puente-alto
mkdir renca

cd la-pintana
touch lista.xls
cd ..

cd maipu
touch lista.xls
cd ..

cd puente-alto
touch lista.xls
cd ..

cd renca
touch lista.xls
cd ..
cd ..
cd sexta-region
touch lista.xls